/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ewaaevljhmkaovvnjgza"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3YWFldmxqaG1rYW92dm5qZ3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2OTQwNDAsImV4cCI6MjA4NjI3MDA0MH0.rH-PxZBRKds6rgbvnx-2naG2uF8ekKb55BuxYnRmw-Y"